server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sgpe}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update   # em prod prefira Flyway/Liquibase
    properties:
      hibernate.jdbc.time_zone: UTC

management:
  endpoints:
    web.exposure.include: health,info
